### ISSUE TITLE
Jelly Sculk crashing player when taking damage from no attacker

### ISSUE THREAD

**Issue by GodschildGaming** [Provismet/Provi-Origins#12]
### Type of Error

Crash

### Description

A player on a server I joined was using the jelly sculk origin and they got stuck in a crash loop due to falling into lava. While this is a issue with the execute command type from origins it self trying to call on a null entity, I found that adding a damage source attacker condition helped prevent the crash.

Original Code: 
```json
"when_hit": {
  "type": "origins:attacker_action_when_hit",
  "entity_action": {
      "type": "origins:execute_command",
      "command": "scoreboard players set @s jellysculk_counter 0"
  }
}
```

the fix:
```json
"when_hit": {
  "type": "origins:attacker_action_when_hit",
  "entity_action": {
      "type": "origins:execute_command",
      "command": "scoreboard players set @s jellysculk_counter 0"
  },
  "damage_condition": {
    "type": "origins:attacker",
    "entity_condition": {
      "type": "origins:exists"
    }
  }
}
```

### Mod Version

1.6.2

### Minecraft Version

1.20.2

### Mod Loader

Fabric

### Steps to Reproduce

1 ) Choose jelly sculk origin
2 ) get set on fire

### Crash Log

```bash
---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 2024-12-23 03:29:49
Description: Ticking player

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1297.method_37908()" because "entity" is null
	at knot//io.github.apace100.apoli.power.factory.action.EntityActions.lambda$register$12(EntityActions.java:162)
	at knot//io.github.apace100.apoli.power.factory.action.ActionFactory$Instance.accept(ActionFactory.java:37)
	at knot//io.github.apace100.apoli.power.AttackerActionWhenHitPower.whenHit(AttackerActionWhenHitPower.java:36)
	at knot//net.minecraft.class_1309.mdd8ad09$apoli$lambda$apoli$invokeHitActions$23$d(class_1309.java:4964)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1242)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at knot//io.github.apace100.apoli.component.PowerHolderComponent.withPowers(PowerHolderComponent.java:160)
	at knot//net.minecraft.class_1309.handler$zcf001$apoli$invokeHitActions(class_1309.java:4964)
	at knot//net.minecraft.class_1309.method_5643(class_1309.java:1271)
	at knot//net.minecraft.class_1657.method_5643(class_1657.java:934)
	at knot//net.minecraft.class_3222.method_5643(class_3222.java:733)
	at knot//net.minecraft.class_1297.method_5670(class_1297.java:520)
	at knot//net.minecraft.class_1309.method_5670(class_1309.java:369)
	at knot//net.minecraft.class_1297.method_5773(class_1297.java:476)
	at knot//net.minecraft.class_1309.method_5773(class_1309.java:2410)
	at knot//net.minecraft.class_1657.method_5773(class_1657.java:286)
	at knot//net.minecraft.class_3222.method_14226(class_3222.java:511)
	at knot//net.minecraft.class_3244.method_18784(class_3244.java:258)
	at knot//net.minecraft.class_2535.method_10754(class_2535.java:379)
	at knot//net.minecraft.class_3242.method_14357(class_3242.java:176)
	at knot//net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:908)
	at knot//net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:820)
	at knot//net.minecraft.class_1132.method_3748(class_1132.java:105)
	at knot//net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:667)
	at knot//net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:263)
	at java.base/java.lang.Thread.run(Thread.java:833)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at knot//io.github.apace100.apoli.power.factory.action.EntityActions.lambda$register$12(EntityActions.java:162)
	at knot//io.github.apace100.apoli.power.factory.action.ActionFactory$Instance.accept(ActionFactory.java:37)
	at knot//io.github.apace100.apoli.power.AttackerActionWhenHitPower.whenHit(AttackerActionWhenHitPower.java:36)
	at knot//net.minecraft.class_1309.mdd8ad09$apoli$lambda$apoli$invokeHitActions$23$d(class_1309.java:4964)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1242)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at knot//io.github.apace100.apoli.component.PowerHolderComponent.withPowers(PowerHolderComponent.java:160)
	at knot//net.minecraft.class_1309.handler$zcf001$apoli$invokeHitActions(class_1309.java:4964)
	at knot//net.minecraft.class_1309.method_5643(class_1309.java:1271)
	at knot//net.minecraft.class_1657.method_5643(class_1657.java:934)
	at knot//net.minecraft.class_3222.method_5643(class_3222.java:733)
	at knot//net.minecraft.class_1297.method_5670(class_1297.java:520)
	at knot//net.minecraft.class_1309.method_5670(class_1309.java:369)
	at knot//net.minecraft.class_1297.method_5773(class_1297.java:476)
	at knot//net.minecraft.class_1309.method_5773(class_1309.java:2410)
	at knot//net.minecraft.class_1657.method_5773(class_1657.java:286)

-- Player being ticked --
Details:
	Entity Type: minecraft:player (net.minecraft.class_3222)
	Entity ID: 258
	Entity Name: BB_The_B
	Entity's Exact location: -7.25, 62.00, -25.93
	Entity's Block location: World: (-8,62,-26), Section: (at 8,14,6 in -1,3,-2; chunk contains blocks -16,-64,-32 to -1,319,-17), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-64,-512 to -1,319,-1)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at knot//net.minecraft.class_3222.method_14226(class_3222.java:511)
	at knot//net.minecraft.class_3244.method_18784(class_3244.java:258)
	at knot//net.minecraft.class_2535.method_10754(class_2535.java:379)
	at knot//net.minecraft.class_3242.method_14357(class_3242.java:176)
	at knot//net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:908)
	at knot//net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:820)
	at knot//net.minecraft.class_1132.method_3748(class_1132.java:105)
	at knot//net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:667)
	at knot//net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:263)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- System Details --
Details:
	Minecraft Version: 1.20.2
	Minecraft Version ID: 1.20.2
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 210081184 bytes (200 MiB) / 912261120 bytes (870 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 7800X3D 8-Core Processor           
	Identifier: AuthenticAMD Family 25 Model 97 Stepping 2
	Microarchitecture: Zen 3
	Frequency (GHz): 4.19
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce RTX 4090
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2684
	Graphics card #0 versionInfo: DriverVersion=32.0.15.6094
	Graphics card #1 name: AMD Radeon(TM) Graphics
	Graphics card #1 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #1 VRAM (MB): 512.00
	Graphics card #1 deviceId: 0x164e
	Graphics card #1 versionInfo: DriverVersion=31.0.24002.92
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 4.80
	Memory slot #0 type: Unknown
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 4.80
	Memory slot #1 type: Unknown
	Virtual memory max (MB): 43738.13
	Virtual memory used (MB): 20169.24
	Swap memory total (MB): 11776.00
	Swap memory used (MB): 0.00
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4096m -Xms256m
	Fabric Mods: 
		additional-armoury: Additional Armoury 1.0.2+1.20.2
			mm: Manningham Mills 2.3
		anim_origins_nx95: Animal Origins 2.3.0
		apocalypse_origins: Apocalypse Origins 0.4.63-1.20.X
		appleskin: AppleSkin 2.5.1+mc1.20.2
			cloth-config: Cloth Config v12 12.0.109
				cloth-basic-math: cloth-basic-math 0.6.1
		combat-plus-core: Combat+ Core 1.1.0+1.20.1
			lilylib: LilyLib 1.1.3+1.20
		entityculling: EntityCulling 1.7.2
		extended-enchanting: Extended Enchanting 1.0.1+1.20.1
		extra-damage-enchantments: Extra Damage Enchantments 1.2.0+1.20.1
		extrade-origins-addon: ExtraDE Origins Addon 1.2.0
		fabric-api: Fabric API 0.91.6+1.20.2
			fabric-api-base: Fabric API Base 0.4.33+fce67b32a0
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.43+b1792f7da0
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.14+b1792f7da0
			fabric-block-api-v1: Fabric Block API (v1) 1.0.12+73761d2ea0
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.1+73761d2ea0
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.43+f4b7e424a0
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.4+86b12645a0
			fabric-command-api-v1: Fabric Command API (v1) 1.2.37+f71b366fa0
			fabric-command-api-v2: Fabric Command API (v2) 2.2.16+b1792f7da0
			fabric-commands-v0: Fabric Commands (v0) 0.2.54+df3654b3a0
			fabric-containers-v0: Fabric Containers (v0) 0.1.81+df3654b3a0
			fabric-content-registries-v0: Fabric Content Registries (v0) 5.0.6+b1792f7da0
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.8+b1792f7da0
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.20+f4b7e424a0
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 13.1.11+b1792f7da0
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.57+b1792f7da0
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.26+b1792f7da0
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.10+b1792f7da0
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.70+df3654b3a0
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.42+a44e16a6a0
			fabric-item-api-v1: Fabric Item API (v1) 2.1.33+b1792f7da0
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.15+e3d2bf3fa0
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.38+f4b7e424a0
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.36+df3654b3a0
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.28+c8b10480a0
			fabric-loot-api-v2: Fabric Loot API (v2) 2.1.1+3ba460fba0
			fabric-message-api-v1: Fabric Message API (v1) 6.0.2+e3d2bf3fa0
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.56+f4b7e424a0
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.6+b1792f7da0
			fabric-models-v0: Fabric Models (v0) 0.4.5+9386d8a7a0
			fabric-networking-api-v1: Fabric Networking API (v1) 3.1.5+f4be560ba0
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 12.1.2+2ff98d3ba0
			fabric-particles-v1: Fabric Particles (v1) 1.1.4+f4b7e424a0
			fabric-recipe-api-v1: Fabric Recipe API (v1) 2.0.14+52b3ebe5a0
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 4.0.12+b1792f7da0
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.1+2034447ca0
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.1+2034447ca0
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.49+df3654b3a0
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.39+73761d2ea0
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.30+f4b7e424a0
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.52+df3654b3a0
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.11+b1792f7da0
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.11+239dafd8a0
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.12+b1792f7da0
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.12+b1792f7da0
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.47+b1792f7da0
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.14+f4b7e424a0
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.13+4944b5a5a0
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 5.0.3+fce67b32a0
		fabric-language-kotlin: Fabric Language Kotlin 1.13.0+kotlin.2.1.0
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 2.1.0
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 2.1.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 2.1.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 2.1.0
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.26.1
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.9.0
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.9.0
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.6.1
			org_jetbrains_kotlinx_kotlinx-io-bytestring-jvm: kotlinx-io-bytestring-jvm 0.6.0
			org_jetbrains_kotlinx_kotlinx-io-core-jvm: kotlinx-io-core-jvm 0.6.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.7.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.7.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.7.3
		fabricloader: Fabric Loader 0.16.9
			mixinextras: MixinExtras 0.4.1
		immediatelyfast: ImmediatelyFast 1.3.3+1.20.4
			net_lenni0451_reflect: Reflect 1.3.4
		java: OpenJDK 64-Bit Server VM 17
		lithium: Lithium 0.12.0
		minecraft: Minecraft 1.20.2
		modernfix: ModernFix 5.10.1+mc1.20.2
		mousetweaks: Mouse Tweaks 2.26
		origins: Origins 1.12.8
			apoli: Apoli 2.11.9
				additionalentityattributes: Additional Entity Attributes 1.5.0+1.20.2
				calio: Calio 1.13.2
					org_quiltmc_parsers_gson: gson 0.2.1
					org_quiltmc_parsers_json: json 0.2.1
				cardinal-components-base: Cardinal Components API (base) 5.3.0
				cardinal-components-entity: Cardinal Components API (entities) 5.3.0
				playerabilitylib: Pal 1.9.0
			reach-entity-attributes: Reach Entity Attributes 2.4.0
		pehkui: Pehkui 3.8.3+1.14.4-1.21
			kanos_config: Kanos Config 0.4.1+1.14.4-1.19.4
		proviorigins: Provi's Origins 1.6.2+1.20.2
		silk-all: Silk (All modules) 1.10.2
			silk-commands: Silk Commands 1.10.2
			silk-core: Silk Core 1.10.2
			silk-game: Silk Game 1.10.2
			silk-igui: Silk Inventory GUI 1.10.2
			silk-nbt: Silk NBT 1.10.2
			silk-network: Silk Network 1.10.2
			silk-persistence: Silk Persistence 1.10.2
		spark: spark 1.10.54
		terralith: Terralith 2.5.4
		veinminer: Veinminer 2.0.3
			de_miraculixx_core_: core 2.0.4
			fabric-permissions-api-v0: fabric-permissions-api 0.2-SNAPSHOT
	Server Running: true
	Player Count: 1 / 8; [class_3222['BB_The_B'/258, l='ServerLevel[New World]', x=-7.25, y=62.00, z=-25.93]]
	Data Packs: vanilla, fabric
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Experimental
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Launched Version: fabric-loader-0.16.9-1.20.2
```

**Comment by Provismet** [comment]
Bug is now fixed in version 1.6.4 for 1.20.2 and 1.20.4.
